// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGM4DFoNE3ttUwN1J-7urhXjtgv274BME',
    appId: '1:816970262025:web:708ba0f495133ffaef7ad8',
    messagingSenderId: '816970262025',
    projectId: 'caera-a27eb',
    authDomain: 'caera-a27eb.firebaseapp.com',
    storageBucket: 'caera-a27eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtKDj8V4SX7afIhKC6QA0uVbBwHZ6WDpg',
    appId: '1:816970262025:android:2aaae4152b176e89ef7ad8',
    messagingSenderId: '816970262025',
    projectId: 'caera-a27eb',
    storageBucket: 'caera-a27eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ3zLlpKnkpaPYxm0K8lJqteQATBufNtw',
    appId: '1:816970262025:ios:d0705e4363fbf27def7ad8',
    messagingSenderId: '816970262025',
    projectId: 'caera-a27eb',
    storageBucket: 'caera-a27eb.appspot.com',
    iosBundleId: 'com.example.carea',
  );
}
